// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SchoolWeb.Models;
using System;

namespace SchoolWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180330094636_new1")]
    partial class new1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolWeb.Models.Admission", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthdate");

                    b.Property<int>("Class");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Guardian");

                    b.Property<string>("GuardianDetails")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("LastSchool")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PerPost")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PerVill")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PerZila")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PrePost")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PreVill")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PreZila")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("StudentNameBan")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("StudentNameEng")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("StudentId");

                    b.ToTable("Admitted");
                });

            modelBuilder.Entity("SchoolWeb.Models.UserAccounts", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account_Type")
                        .IsRequired();

                    b.Property<string>("ComfirmPassword");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("StudentId");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("UserAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
